name: Publish

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        run: dotnet restore ./Login_Regester.sln

      - name: Build
        run: dotnet build ./Login_Regester.sln --configuration Release

      - name: Publish
        run: dotnet publish ./Login_Regester.sln --configuration Release -o build
